import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const kombatFont = localFont({ src: "../public/fonts/Kombat11-Regular.woff2" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={kombatFont.className + " w-screen h-screen"}>
        {children}
      </body>
    </html>
  );
}
